const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:"chrome"});
 const page=await browser.newPage({viewport:{width:375,height:812}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.NESTLY_URL||'https://nestly.test/';
 if(!process.env.NESTLY_URL)await page.route('https://nestly.test/**',route=>route.fulfill({contentType:'text/html',body:fs.readFileSync('index.html','utf8')}));
 await page.goto(url);
 const date=await page.evaluate(()=>localDate());
 const legacy=[{id:'legacy-food',type:'food',date,time:'12:00',foodName:'南瓜',amount:'105',note:'舊備註',extra:'keep'},{id:'legacy-pee',type:'pee',date,time:'13:00',peeAmount:'正常'},{id:'legacy-milk',type:'milk',date,time:'10:00',amount:'180',milkKind:'配方奶'}];
 await page.evaluate(data=>localStorage.setItem('nestly_records_v02',JSON.stringify(data)),legacy);
 await page.reload();
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('nestly_records_v02'))),legacy);
 await page.locator('#timeline [data-id="legacy-food"]').click();
 assert.equal(await page.locator('[name=ingredientName]').inputValue(),'南瓜');
 assert.equal(await page.locator('[name=ingredientAmount]').inputValue(),'105');
 await page.locator('#addIngredient').click();
 await page.locator('[name=ingredientName]').nth(1).fill('雞肉');
 await page.locator('[name=ingredientAmount]').nth(1).fill('25.5');
 await page.locator('.save').click();
 let data=await page.evaluate(()=>JSON.parse(localStorage.getItem('nestly_records_v02')));
 assert.equal(data.length,3);assert.equal(data[0].ingredients.length,2);assert.equal(data[0].extra,'keep');assert.equal(data[0].note,'舊備註');
 await page.reload();
 assert.match(await page.locator('#timeline [data-id="legacy-food"]').innerText(),/雞肉 25.5 g/);
 await page.locator('#timeline [data-id="legacy-food"]').click();
 await page.locator('.remove-ingredient').nth(1).click();await page.locator('.save').click();
 await page.locator('#timeline [data-id="legacy-pee"]').click();
 assert.equal(await page.locator('[name=peeColor]').inputValue(),'');
 await page.locator('[name=peeColor]').selectOption('淡黃');await page.locator('.save').click();await page.reload();
 assert.match(await page.locator('#timeline [data-id="legacy-pee"]').innerText(),/淡黃/);
 await page.locator('#addBtn').click();await page.locator('[data-type=food]').click();
 const fields=await page.locator('.ingredient input').evaluateAll(xs=>xs.map(x=>x.name));assert.deepEqual(fields,['ingredientName','ingredientAmount']);
 await page.locator('[name=ingredientName]').fill('米飯');await page.locator('[name=ingredientAmount]').fill('60');await page.locator('#addIngredient').click();await page.locator('[name=ingredientName]').nth(1).fill('青菜');await page.locator('[name=ingredientAmount]').nth(1).fill('20');await page.locator('.save').click();
 data=await page.evaluate(()=>JSON.parse(localStorage.getItem('nestly_records_v02')));assert.equal(data.length,4);assert.equal(data[3].ingredients.length,2);
 await page.locator(`#timeline [data-id="${data[3].id}"]`).click();page.once('dialog',d=>d.accept());await page.locator('#deleteRecord').click();
 await page.locator('#addBtn').click();await page.locator('[name=amount]').fill('120');await page.locator('.save').click();await page.reload();assert.match(await page.locator('#sumMilk').innerText(),/300/);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('#addBtn').click();await page.locator('[data-type=sleep]').click();
 assert.equal(await page.locator('[name=time]').count(),0);
 await page.locator('[name=startTime]').fill('09:54');
 assert.equal(await page.locator('.save').innerText(),'開始睡眠');
 await page.locator('.save').click();await page.reload();
 const sleep=page.locator('#timeline .record').filter({hasText:'睡眠中'});
 assert.equal(await sleep.count(),1);await sleep.click();
 assert.equal(await page.locator('[name=startTime]').inputValue(),'09:54');
 await page.locator('[name=endTime]').fill('11:20');
 assert.equal(await page.locator('.save').innerText(),'結束睡眠');
 await page.locator('.save').click();await page.reload();
 const done=page.locator('#timeline .record').filter({hasText:'09:54–11:20｜1 小時 26 分'});
 assert.equal(await done.count(),1);await done.click();
 assert.equal(await page.locator('.save').innerText(),'儲存修改');
 await page.locator('[name=startTime]').fill('23:30');await page.locator('[name=endTime]').fill('06:15');await page.locator('.save').click();
 assert.match(await page.locator('#timeline').innerText(),/23:30–隔日 06:15｜6 小時 45 分/);
 await page.evaluate(date=>{const r=JSON.parse(localStorage.getItem('nestly_records_v02'));r.push({id:'old-sleep',type:'sleep',date,time:'08:00',endTime:'09:00',note:'legacy sleep'});localStorage.setItem('nestly_records_v02',JSON.stringify(r))},date);
 await page.reload();await page.locator('#timeline [data-id="old-sleep"]').click();
 assert.equal(await page.locator('[name=startTime]').inputValue(),'08:00');await page.locator('.save').click();
 assert.match(await page.locator('#timeline [data-id="old-sleep"]').innerText(),/1 小時 0 分/);
 assert.deepEqual(errors,[]);
 console.log('PASS: legacy data unchanged on load; meal add/edit/remove/delete; urine color; reload persistence; milk totals; mobile width; no browser errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
